services:
  db:
    restart: always
    container_name: project_db
    image: postgres:14.19-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=UQO123?
      - POSTGRES_DB=postgres
    ports: 
      - 5432:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: project_backend
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend
    depends_on:
      - db
    ports:
      - 8000:8000

volumes:
  postgres_data: