services:
  db:
    restart: always
    container_name: project_db
    image: postgres:14.19-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=UQO123?
      - POSTGRES_DB=postgres
    ports: 
      - 5433:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: project_backend
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend
    depends_on:
      - db
    ports:
      - 8000:8000
  frontend:
    container_name: project_frontend
    volumes:
      - ./frontend:/home/node
    build: ./frontend
    working_dir: /home/node
  nginx:
    container_name: project_nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 5173:8080
volumes:
  postgres_data: