# Generated by Django 5.2.6 on 2025-09-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
